@startuml System context diagram of "Family archive"
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title Container diagram of "Family archive management system"

Person(client, "Client", "People that need to store photos and videos long-term as a backup")

System_Boundary(archive, "Archive management system") {
  Container(landing, "Landing page", "HTML/CSS/JS", "Allows a client to find the product. Has SEO optimized blog, pricing, demo.")
  Container(spa, "SPA", "Svelte", "Allows a client to use the archive management system, to upload, restore, download arvhives.")
  Container(backend, "Web server", "Go on Lambda", "Handles all business logic, tracks file states and consistency.")
  Container(archival, "Archival job", "Go on Fargate", "Creates cold archives.")
  Container(s3, "Object file storage", "Amazon S3")
  ContainerDb(db, "Metadata database", "MySQL", "Stores files' metadata and state.")
}

System_Boundary(aws, "Infrastructure provider system") {
  Container_Ext(eventbridge, "Event bus/Scheduler", "Amazon EventBridge")
}

System_Ext(ia, "Payment system", "Provides internet acquiring services. Allows clients to pay for the services.")
System_Ext(mail, "E-mail system", "Allows communication with client via e-mail.")


Rel_D(landing, spa, "Redirects the client to", "HTTPS")
Rel_D(spa, backend, "Calls API", "HTTPS")
Rel_L(backend, db, "Stores/reads file state to/from")
Rel_D(backend, ia, "Create invoices using")
Rel_D(backend, mail, "Sends mail using")
Rel_L(backend, eventbridge, "Schedules archival jobs using")
Rel_U(eventbridge, archival, "Triggers")
Rel_U(archival, s3, "Stores photos and videos, hosts servers, lambdas using")


Rel_D(client, landing, "Learns about the application, pricing, features.")
Rel_D(client, s3, "Uploads photos and videos directly to temporary storage")

SHOW_LEGEND()

@enduml